# Generated by Django 5.2.11 on 2026-02-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="section_index",
            field=models.IntegerField(default=0),
        ),
    ]
